version: 0.2
env:
  variables:
    AWS_REGION: "us-east-1"
    EKS_CLUSTER: "my-eks-cluster"
phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Using AWS Region: $AWS_REGION"
      - echo "Using EKS Cluster: $EKS_CLUSTER"
      - aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER
  build:
    commands:
      - echo "Generating Kubernetes Bill of Materials (BoM)"
      - kubectl cluster-info dump > cluster_info.json
      - kubectl get nodes -o json > nodes.json
      - kubectl get deployments --all-namespaces -o json > deployments.json
      - kubectl get services --all-namespaces -o json > services.json
      - kubectl get configmaps --all-namespaces -o json > configmaps.json
      - kubectl get secrets --all-namespaces -o json > secrets.json
      - kubectl get pods --all-namespaces -o json | jq '[.items[] | {namespace: .metadata.namespace, pod: .metadata.name, containers: [.spec.containers[].image]}]' > container_images.json
      - jq -s '{cluster_info: .[0], nodes: .[1], deployments: .[2], services: .[3], configmaps: .[4], secrets: .[5], container_images: .[6]}' cluster_info.json nodes.json deployments.json services.json configmaps.json secrets.json container_images.json > k8s_bom.json
  post_build:
    commands:
      - echo "Uploading BoM to S3"
      - aws s3 cp k8s_bom.json s3://my-k8s-bom-storage-bucket-rajani-imp-assignment/latest_k8s_bom.json
artifacts:
  files:
    - k8s_bom.json