version: 0.2
env:
  variables:
    AWS_REGION: "us-east-1"
    EKS_CLUSTER: "mynewk8scluster"

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli jq

  pre_build:
    commands:
      - echo "Updating kubeconfig..."
      - aws eks --region "$AWS_REGION" update-kubeconfig --name "$EKS_CLUSTER"
      - aws sts get-caller-identity
      - which aws-iam-authenticator
  build:
    commands:
      - echo "Running Kubernetes BoM generator script..."
      - chmod +x scripts/bom-generator.sh
      - ./scripts/bom-generator.sh

  post_build:
    commands:
      - echo "BoM process completed successfully."

artifacts:
  files:
    - k8s_bom.json